Fix typos
laravel/vapor-core pull request #172
Opened 2024-01-18 11:34 UTC by szepeviktor

Found 2 misspellings.

2024-01-18 11:40 UTC, nunomaduro requested changes

2024-01-18 11:40 UTC, nunomaduro commented on src/Queue/JobAttempts.php
> +        return 'laravel_vapor_job_attempts:'.$jobId;
cc @joedixon this is a breaking change.

2024-02-16 13:30 UTC, joedixon commented
Thanks for the contribution. I have reverted the cache key change as I would like to try to find a solution which doesn't risk the loss of existing job attempts.

The rest looks good to me.

2024-02-16 15:01 UTC, joedixon approved these changes

2024-02-16 17:41 UTC, merged